### ISSUE TITLE
Possible memory leaks when using ref_malloc_init.

### ISSUE THREAD

**Issue by tluio** [nasa/refine#3]
We have found some possible memory leaks through static analysis. They are introduced when using the macro ref_malloc_init() in refine/src/ref_subdiv.c. Here is an example.
In function ref_subdiv_new_node() at lines 945-947, ref_malloc_init() is used for three times. My understanding is that it will allocate a heap object,  and the failure of the allocation will cause the function to return. Therefore, if ref_malloc_init() at line 946 fails, memory allocated at line 945 will leak, and if ref_malloc_init() at line 947 fails, memory allocated at line 945 and 946 will both leak.
Aslo I am not sure whether the macro RSS() will cause the function to return. If so, memory allocated at line 1036 will also leak.

**Comment by mikepark** [comment]
What static analysis tool are you using? I'd like to include the same tool in my continuous integration pipeline.

**Comment by tluio** [comment]
> What static analysis tool are you using? I'd like to include the same tool in my continuous integration pipeline.

Thanks for your interest! I used a static analysis tool implemented by our group. Our tool is still under development, and we consider releasing it in the future :)

**Comment by mikepark** [comment]
if the malloc fails it will free to prevent leaks. Thank you for the suggestion.
