### ISSUE TITLE
Possible null dereference in refine/src/ref_facelift.c.

### ISSUE THREAD

**Issue by tluio** [nasa/refine#4]
We have found a possible null dereference through static analysis in refine/src/ref_facelift.c.
In the function ref_facelift_eval_at() at line 707, NULL is assigned to _ref_cell_. I am not sure if the variable _type_ must be **REF_GEOM_EDGE**  or **REF_GEOM_FACE**. If not, _ref_cell_ is also NULL at line 724. However, it is dereferenced in the function ref_cell_shape().

**Comment by mikepark** [comment]
Added an assert that ref_cell is not NULL before attempting to dereference. Thank you for suggestion.
